version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/nonprofit_db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nonprofit_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:

networks:
  nonprofit_network:
    driver: bridge

services:
  web:
    # ... other configurations ...
    networks:
      - nonprofit_network
  db:
    # ... other configurations ...
    networks:
      - nonprofit_network