# business_activity_code_mapper.py

class BusinessActivityCodeMapper:
    def __init__(self):
        try:
            from irs_990_toolkit import BusinessActivityCodeMapper as IRSBusinessActivityCodeMapper
            self.mapping = IRSBusinessActivityCodeMapper.mapping
        except ImportError:
            print("irs-990-toolkit not found. Using default mapping.")
            self.mapping = {
                '110000': 'Agriculture, forestry, hunting and fishing',
                '111000': 'Crop production',
                '211110': 'Oil and gas extraction',
                '211120': 'Crude petroleum extraction',
                '211130': 'Natural gas extraction',
                '212000': 'Mining (except oil and gas)',
                '221000': 'Utilities',
                '230000': 'Construction',
                '236000': 'Construction of buildings',
                '310000': 'Manufacturing',
                '323100': 'Printing and related support activities',
                '339110': 'Medical equipment and supplies manufacturing',
                '423000': 'Merchant wholesalers, durable goods',
                '424000': 'Merchant wholesalers, nondurable goods',
                '441100': 'Automobile dealers',
                '442000': 'Furniture and home furnishings stores',
                '444100': 'Building materials and supplies dealers',
                '445100': 'Grocery stores',
                '445200': 'Specialty food stores',
                '446110': 'Pharmacies and drug stores',
                '446199': 'All other health and personal care stores',
                '448000': 'Clothing and clothing accessories stores',
                '451110': 'Sporting goods stores',
                '451211': 'Book stores',
                '452000': 'General merchandise stores',
                '453000': 'Miscellaneous store retailers',
                '453220': 'Gift, novelty, and souvenir stores',
                '453310': 'Used merchandise stores',
                '454110': 'Electronic shopping and mail-order houses',
                '480000': 'Transportation',
                '485000': 'Transit and ground passenger transportation',
                '493000': 'Warehousing and storage',
                '511110': 'Newspaper publishers (except Internet)',
                '511120': 'Periodical publishers (except Internet)',
                '511130': 'Book publishers (except Internet)',
                '511140': 'Directory and mailing list publishers',
                '511190': 'Other publishers (except Internet)',
                '512000': 'Motion picture and sound recording industries',
                '515100': 'Radio and television broadcasting (except Internet)',
                '517000': 'Telecommunications (including paging, cellular, satellite, cable, other telecommunications, and Internet service providers)',
                '519100': 'Other information services (including news syndicates and libraries)',
                '519130': 'Internet Publishing and Broadcast',
                '518210': 'Data Processing, Hosting, and Related Services',
                '522100': 'Depository credit intermediation (including commercial banking, savings institutions, and credit unions)',
                '522200': 'Nondepository credit intermediation (including credit card issuing and sales financing)',
                '522110': 'Credit card issuing',
                '522220': 'Sales Financing',
                '522291': 'Consumer lending',
                '522292': 'Real estate credit',
                '522298': 'Other nondepository credit intermediation',
                '523000': 'Securities, commodity contracts, and other financial investments and related activities',
                '523920': 'Portfolio management',
                '523930': 'Investment advice',
                '524113': 'Direct life insurance carriers',
                '524114': 'Direct health and medical insurance carriers',
                '524126': 'Direct property and casualty insurance carriers',
                '524130': 'Reinsurance carriers',
                '524292': 'Third-party administration of insurance and pension funds',
                '524298': 'All other insurance-related activities',
                '525100': 'Insurance and employee benefit funds',
                '525920': 'Trusts, estates, and agency accounts',
                '525990': 'Other Financial vehicles (including mortgage REITs)',
                '531110': 'Lessors of residential buildings and dwellings (including equity REITs)',
                '531120': 'Lessors of nonresidential buildings (except minwarehouses) (including equity REITs)',
                '531190': 'Lessors of other real estate property (including equity REITs)',
                '531310': 'Real estate property managers',
                '531390': 'Other activities related to real estate',
                '532000': 'Rental and leasing services',
                '532420': 'Office machinery and equipment rental and leasing',
                '533110': 'Lessors of nonfinancial intangible assets (except copyrighted works)',
                '541100': 'Legal services',
                '541990': 'Consumer credit counseling services',
                '541200': 'Accounting, tax preparation, bookkeeping, and payroll services',
                '541300': 'Architectural, engineering, and related services',
                '541380': 'Testing laboratories',
                '541511': 'Custom computer programming services',
                '541519': 'Other computer-related services',
                '541610': 'Management consulting services',
                '541700': 'Scientific research and development services',
                '541800': 'Advertising and related services',
                '541860': 'Direct mail advertising',
                '541900': 'Other professional, scientific, and technical services',
                '551111': 'Offices of bank holding companies',
                '551112': 'Offices of other holding companies',
                '561000': 'Administrative and support services',
                '561300': 'Employment services',
                '561439': 'Other business service centers',
                '561499': 'All other business support services',
                '561500': 'Travel arrangement and reservation services',
                '561520': 'Tour operators',
                '561700': 'Services to buildings and dwellings',
                '562000': 'Waste management and remediation services (sanitary services)',
                '611420': 'Computer training',
                '611430': 'Professional and management development training',
                '611600': 'Other schools and instruction (other than elementary and secondary schools or colleges and universities, which should select a code to describe their unrelated activities)',
                '611710': 'Educational support services',
                '621110': 'Offices of physicians',
                '621300': 'Offices of other health practitioners',
                '621400': 'Outpatient care centers',
                '621500': 'Medical and diagnostic laboratories',
                '621610': 'Home health care services',
                '621910': 'Ambulance services',
                '621990': 'All other ambulatory health care services',
                '623000': 'Nursing and residential care facilities',
                '623990': 'Other residential care facilities',
                '624100': 'Individual and family services',
                '624110': 'Community centers (except rec. only), youth Adoption agencies',
                '624200': 'Community food and housing, and emergency and other relief services',
                '624210': 'Meal delivery programs, Soup kitchens, or Food banks',
                '624310': 'Vocational rehabilitation services',
                '624410': 'Child day care services',
                '711110': 'Theater companies and dinner theaters',
                '711120': 'Dance companies',
                '711130': 'Musical groups and artists',
                '711190': 'Other performing art companies',
                '711210': 'Spectator sports (including sports clubs and racetracks)',
                '711300': 'Promoters of performing arts, sports and similar events',
                '713110': 'Amusement and theme parks',
                '713200': 'Gambling industries',
                '713910': 'Golf courses and country clubs',
                '713940': 'Fitness and recreational sports centers',
                '713990': 'All other amusement and recreation industries (including skiing facilities, marinas, and bowling centers)',
                '721000': 'Accommodation',
                '721110': 'Hotels (except casino hotels) and motels',
                '721210': 'RV (recreational vehicle) parks and recreational camps',
                '721310': 'Rooming and boarding houses, dormitories, and workers\' camps',
                '722320': 'Caterers',
                '722440': 'Drinking places (alcoholic beverages)',
                '722511': 'Full-service restaurants',
                '722513': 'Limited-service restaurants',
                '722514': 'Cafeterias and buffets',
                '722515': 'Snack and non-alcoholic beverage bars',
                '811000': 'Repair and maintenance',
                '812300': 'Drycleaning and laundry services',
                '812900': 'Other personal services',
                '812930': 'Parking lots and garages',
                '900001': 'Investment activities of section 501(c)(7), (9), or (17) organizations',
                '900002': 'Rental of personal property',
                '900003': 'Passive income activities with controlled organizations'
            }
    
    def get_description(self, code):
        return self.mapping.get(code, None)
